In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [71]:
delivery = pd.read_csv("../data/raw/deliveries.csv")
match = pd.read_csv("../data/raw/matches.csv")

In [72]:
match.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [73]:
match.shape

(756, 18)

In [74]:
delivery.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [75]:
total_score_df = delivery.groupby(["match_id","inning"]).sum()["total_runs"].reset_index()

In [76]:
total_score_df = total_score_df[total_score_df["inning"] == 1]

In [77]:
total_score_df['total_runs'] = total_score_df['total_runs'] + 1

In [78]:
total_score_df

      match_id  inning  total_runs
0            1       1         208
2            2       1         185
4            3       1         184
6            4       1         164
8            5       1         158
...        ...     ...         ...
1518     11347       1         144
1520     11412       1         137
1522     11413       1         172
1524     11414       1         156
1526     11415       1         153

[756 rows x 3 columns]

In [79]:
match_df = match.merge(total_score_df[["match_id","total_runs"]],left_on = "id", right_on = "match_id")

In [80]:
match_df

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_runs
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,208
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,2,185
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,3,184
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,4,164
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,5,158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi,11347,144
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould,11412,137
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN,11413,172
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin,11414,156
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong,11415,153

In [81]:
match_df["team1"].unique()

<StringArray>
[        'Sunrisers Hyderabad',              'Mumbai Indians',
               'Gujarat Lions',      'Rising Pune Supergiant',
 'Royal Challengers Bangalore',       'Kolkata Knight Riders',
            'Delhi Daredevils',             'Kings XI Punjab',
         'Chennai Super Kings',            'Rajasthan Royals',
             'Deccan Chargers',        'Kochi Tuskers Kerala',
               'Pune Warriors',     'Rising Pune Supergiants',
              'Delhi Capitals']
Length: 15, dtype: str

In [82]:
 teams = [
     "Sunrisers Hyderabad",
     'Mumbai Indians',
     'Royal Challengers Bangalore', 
     'Kolkata Knight Riders',
     'Kings XI Punjab',
     'Chennai Super Kings',
     'Rajasthan Royals',
     'Delhi Capitals'
 ]

In [83]:
match_df["team1"] = match_df["team1"].str.replace("Delhi Daredevils", "Delhi Capitals")
match_df["team2"] = match_df["team2"].str.replace("Delhi Daredevils", "Delhi Capitals")
match_df["team1"] = match_df["team1"].str.replace('Deccan Chargers',  'Sunrisers Hyderabad')
match_df["team2"] = match_df["team2"].str.replace('Deccan Chargers',  'Sunrisers Hyderabad')

In [84]:
match_df = match_df[match_df["team1"].isin(teams)]
match_df = match_df[match_df["team2"].isin(teams)]

In [127]:
match_df

     match_id           city                       winner  total_runs
0           1      Hyderabad          Sunrisers Hyderabad         208
4           5      Bangalore  Royal Challengers Bangalore         158
6           7         Mumbai               Mumbai Indians         179
7           8         Indore              Kings XI Punjab         149
9          10         Mumbai               Mumbai Indians         159
..        ...            ...                          ...         ...
751     11347         Mumbai               Mumbai Indians         144
752     11412        Chennai               Mumbai Indians         137
753     11413  Visakhapatnam               Delhi Capitals         172
754     11414  Visakhapatnam          Chennai Super Kings         156
755     11415      Hyderabad               Mumbai Indians         153

[626 rows x 4 columns]

In [86]:
match_df = match_df[match_df["dl_applied"] == 0]

In [87]:
match_df = match_df[['match_id','city','winner','total_runs']]

In [88]:
delivery_df = match_df.merge(delivery,on = 'match_id')

In [89]:
delivery_df = delivery_df[delivery_df['inning'] == 2]

In [96]:
delivery_df.head(50)

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,runs_left,ball_left,is_wicket,wickets_fallen,wickets_left
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,1,NaN,NaN,NaN,1,207,119,0,0,10
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,NaN,NaN,NaN,1,207,118,0,0,10
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,NaN,NaN,NaN,1,207,117,0,0,10
128,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,2,NaN,NaN,NaN,3,205,116,0,0,10
129,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,4,NaN,NaN,NaN,7,201,115,0,0,10
130,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,6,Mandeep Singh,...,4,NaN,NaN,NaN,11,197,114,0,0,10
131,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,1,CH Gayle,...,0,NaN,NaN,NaN,11,197,113,0,0,10
132,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,2,CH Gayle,...,0,NaN,NaN,NaN,11,197,112,0,0,10
133,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,3,CH Gayle,...,1,NaN,NaN,NaN,12,196,111,0,0,10
134,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,4,Mandeep Singh,...,0,NaN,NaN,NaN,12,196,110,0,0,10
135,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,5,Mandeep Singh,...,0,NaN,NaN,NaN,12,196,109,0,0,10
136,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,6,Mandeep Singh,...,0,NaN,NaN,NaN,12,196,108,0,0,10
137,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,1,CH Gayle,...,0,NaN,NaN,NaN,12,196,107,0,0,10
138,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,2,CH Gayle,...,4,NaN,NaN,NaN,16,192,106,0,0,10
139,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,3,CH Gayle,...,1,NaN,NaN,NaN,17,191,105,0,0,10
140,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,4,Mandeep Singh,...,4,NaN,NaN,NaN,21,187,104,0,0,10
141,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,5,Mandeep Singh,...,1,NaN,NaN,NaN,22,186,103,0,0,10
142,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,6,CH Gayle,...,6,NaN,NaN,NaN,28,180,102,0,0,10
143,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,1,Mandeep Singh,...,1,NaN,NaN,NaN,29,179,101,0,0,10
144,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,2,CH Gayle,...,6,NaN,NaN,NaN,35,173,100,0,0,10
145,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,3,CH Gayle,...,2,NaN,NaN,NaN,37,171,99,0,0,10
146,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,4,CH Gayle,...,1,NaN,NaN,NaN,38,170,98,0,0,10
147,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,5,CH Gayle,...,0,NaN,NaN,NaN,38,170,97,0,0,10
148,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,6,CH Gayle,...,1,NaN,NaN,NaN,39,169,96,0,0,10
149,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,7,Mandeep Singh,...,4,NaN,NaN,NaN,43,165,95,0,0,10
150,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,1,CH Gayle,...,0,NaN,NaN,NaN,43,165,95,0,0,10
151,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,2,CH Gayle,...,0,NaN,NaN,NaN,43,165,94,0,0,10
152,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,3,CH Gayle,...,0,NaN,NaN,NaN,43,165,93,0,0,10
153,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,4,CH Gayle,...,1,NaN,NaN,NaN,44,164,92,0,0,10
154,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,5,CH Gayle,...,0,NaN,NaN,NaN,44,164,91,0,0,10
155,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,6,CH Gayle,...,0,NaN,NaN,NaN,44,164,90,0,0,10
156,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,7,CH Gayle,...,4,NaN,NaN,NaN,48,160,89,0,0,10
157,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,1,Mandeep Singh,...,0,NaN,NaN,NaN,48,160,89,0,0,10
158,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,2,Mandeep Singh,...,4,NaN,NaN,NaN,52,156,88,0,0,10
159,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,3,Mandeep Singh,...,0,NaN,NaN,NaN,52,156,87,0,0,10
160,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,4,Mandeep Singh,...,0,Mandeep Singh,bowled,NaN,52,156,86,1,1,9
161,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,5,TM Head,...,2,NaN,NaN,NaN,54,154,85,0,1,9
162,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,6,TM Head,...,0,NaN,NaN,NaN,54,154,84,0,1,9
163,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,1,CH Gayle,...,0,NaN,NaN,NaN,54,154,83,0,1,9
164,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,2,CH Gayle,...,6,NaN,NaN,NaN,60,148,82,0,1,9
165,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,3,CH Gayle,...,0,CH Gayle,caught,DA Warner,60,148,81,1,2,8
166,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,4,TM Head,...,0,NaN,NaN,NaN,60,148,80,0,2,8
167,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,5,TM Head,...,1,NaN,NaN,NaN,61,147,79,0,2,8
168,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,6,KM Jadhav,...,0,NaN,NaN,NaN,61,147,78,0,2,8
169,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,1,TM Head,...,4,NaN,NaN,NaN,65,143,77,0,2,8
170,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,2,TM Head,...,2,NaN,NaN,NaN,67,141,76,0,2,8
171,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,3,TM Head,...,1,NaN,NaN,NaN,68,140,75,0,2,8
172,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,4,KM Jadhav,...,1,NaN,NaN,NaN,69,139,74,0,2,8
173,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,5,TM Head,...,1,NaN,NaN,NaN,70,138,73,0,2,8
174,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,6,KM Jadhav,...,4,NaN,NaN,NaN,74,134,72,0,2,8

In [97]:
 delivery_df["current_score"] =delivery_df.groupby('match_id')['total_runs_y'].cumsum()

In [98]:
delivery_df["runs_left"] = delivery_df["total_runs_x"] - delivery_df['current_score']

In [99]:
delivery_df["ball_left"] = 120 - ((delivery_df['over'] - 1) * 6 + delivery_df['ball'])

In [100]:
 delivery_df

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,runs_left,ball_left,is_wicket,wickets_fallen,wickets_left
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,1,NaN,NaN,NaN,1,207,119,0,0,10
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,NaN,NaN,NaN,1,207,118,0,0,10
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,NaN,NaN,NaN,1,207,117,0,0,10
128,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,2,NaN,NaN,NaN,3,205,116,0,0,10
129,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,4,NaN,NaN,NaN,7,201,115,0,0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149573,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,1,NaN,NaN,NaN,152,1,4,0,5,5
149574,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,2,NaN,NaN,NaN,154,-1,3,0,5,5
149575,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,1,SR Watson,run out,KH Pandya,155,-2,2,1,6,4
149576,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,2,NaN,NaN,NaN,157,-4,1,0,6,4
149577,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,0,SN Thakur,lbw,NaN,157,-4,0,1,7,3

In [102]:
delivery_df['is_wicket'] = delivery_df['player_dismissed'].notnull().astype(int)
delivery_df['wickets_fallen'] = delivery_df.groupby('match_id')['is_wicket'].cumsum()
delivery_df['wickets_left'] = 10 - delivery_df['wickets_fallen']
delivery_df[['player_dismissed', 'is_wicket', 'wickets_fallen', 'wickets_left']].tail(5)

       player_dismissed  is_wicket  wickets_fallen  wickets_left
149573              NaN          0               5             5
149574              NaN          0               5             5
149575        SR Watson          1               6             4
149576              NaN          0               6             4
149577        SN Thakur          1               7             3

In [105]:
delivery_df["crr"] = (delivery_df["current_score" ] * 6)/(120 - delivery_df["ball_left"])

In [106]:
delivery_df['rrr'] = (delivery_df['runs_left'] * 6)/ delivery_df["ball_left"]

In [107]:
delivery_df

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,dismissal_kind,fielder,current_score,runs_left,ball_left,is_wicket,wickets_fallen,wickets_left,crr,rrr
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,NaN,NaN,1,207,119,0,0,10,6.000000,10.436975
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,NaN,NaN,1,207,118,0,0,10,3.000000,10.525424
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,NaN,NaN,1,207,117,0,0,10,2.000000,10.615385
128,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,NaN,NaN,3,205,116,0,0,10,4.500000,10.603448
129,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,NaN,NaN,7,201,115,0,0,10,8.400000,10.486957
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149573,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,NaN,NaN,152,1,4,0,5,5,7.862069,1.500000
149574,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,NaN,NaN,154,-1,3,0,5,5,7.897436,-2.000000
149575,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,run out,KH Pandya,155,-2,2,1,6,4,7.881356,-6.000000
149576,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,NaN,NaN,157,-4,1,0,6,4,7.915966,-24.000000
149577,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,lbw,NaN,157,-4,0,1,7,3,7.850000,-inf

In [108]:
def result(row):
    return 1 if row["batting_team"] == row['winner'] else 0

In [111]:
delivery_df['result'] = delivery_df.apply(result, axis = 1)

In [116]:
final_df = delivery_df[["batting_team", "bowling_team", "city", "runs_left", "ball_left", "wickets_left", "total_runs_x", "crr", "rrr", "result"]]

In [117]:
final_df.sample(final_df.shape[0])

,batting_team,bowling_team,city,runs_left,ball_left,wickets_left,total_runs_x,crr,rrr,result
46288,Chennai Super Kings,Kings XI Punjab,Dharamsala,187,110,10,193,3.600000,10.200000,1
61604,Kolkata Knight Riders,Kings XI Punjab,Kolkata,62,52,7,135,6.441176,7.153846,0
136121,Rajasthan Royals,Kings XI Punjab,Jaipur,132,80,10,201,10.350000,9.900000,0
135930,Mumbai Indians,Delhi Capitals,Mumbai,65,24,4,220,9.687500,16.250000,0
128955,Mumbai Indians,Kings XI Punjab,Indore,128,65,9,185,6.218182,11.815385,1
...,...,...,...,...,...,...,...,...,...,...
116167,Mumbai Indians,Royal Challengers Bangalore,Mumbai,8,15,6,171,9.314286,3.200000,1
101695,Sunrisers Hyderabad,Chennai Super Kings,Chennai,78,24,6,210,8.250000,19.500000,0
114217,Kolkata Knight Riders,Delhi Daredevils,Kolkata,64,96,10,99,8.750000,4.000000,1
87539,Rajasthan Royals,Sunrisers Hyderabad,Abu Dhabi,17,12,5,134,6.500000,8.500000,1
69038,Mumbai Indians,Royal Challengers Bangalore,Bangalore,145,90,7,172,5.400000,9.666667,1

In [126]:
final_df.sample()

,batting_team,bowling_team,city,runs_left,ball_left,wickets_left,total_runs_x,crr,rrr,result
86978,Royal Challengers Bangalore,Delhi Daredevils,Sharjah,122,96,9,146,6.0,7.625,1

In [128]:
final_df['bowling_team'].unique()

<StringArray>
[        'Sunrisers Hyderabad', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders',             'Kings XI Punjab',
            'Delhi Daredevils',              'Mumbai Indians',
         'Chennai Super Kings',            'Rajasthan Royals',
             'Deccan Chargers',              'Delhi Capitals']
Length: 10, dtype: str

In [134]:
team_map = {
    'Delhi Daredevils': 'Delhi Capitals',
    'Deccan Chargers': 'Sunrisers Hyderabad'
}
for col in ['batting_team', 'bowling_team']:
    final_df[col] = final_df[col].replace(team_map)

In [131]:
final_df.sample(final_df.shape[0])

,batting_team,bowling_team,city,runs_left,ball_left,wickets_left,total_runs_x,crr,rrr,result
137830,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,214,104,9,234,7.500000,12.346154,0
112647,Kolkata Knight Riders,Rajasthan Royals,Mumbai,170,97,8,200,7.826087,10.515464,0
103870,Chennai Super Kings,Mumbai Indians,Mumbai,63,66,8,184,13.444444,5.727273,1
124095,Chennai Super Kings,Kings XI Punjab,Mohali,103,57,7,199,9.142857,10.842105,0
137172,Sunrisers Hyderabad,Rajasthan Royals,Hyderabad,26,23,5,204,11.010309,6.782609,1
...,...,...,...,...,...,...,...,...,...,...
94441,Kolkata Knight Riders,Kings XI Punjab,Cuttack,60,56,9,150,8.437500,6.428571,1
93248,Kolkata Knight Riders,Delhi Capitals,Delhi,17,20,9,161,8.640000,5.100000,1
28671,Rajasthan Royals,Sunrisers Hyderabad,Kimberley,58,7,1,167,5.787611,49.714286,0
128252,Delhi Capitals,Chennai Super Kings,Pune,87,30,6,219,8.800000,17.400000,0
73687,Kolkata Knight Riders,Rajasthan Royals,Jaipur,102,78,6,145,6.142857,7.846154,0

In [133]:
final_df.sample()

,batting_team,bowling_team,city,runs_left,ball_left,wickets_left,total_runs_x,crr,rrr,result
98071,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata,157,82,9,196,6.157895,11.487805,0

In [135]:
final_df['bowling_team'].unique()

<StringArray>
[        'Sunrisers Hyderabad', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders',             'Kings XI Punjab',
              'Delhi Capitals',              'Mumbai Indians',
         'Chennai Super Kings',            'Rajasthan Royals']
Length: 8, dtype: str

In [139]:
final_df.to_csv('../data/processed/final_df.csv', index=False)