In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [59]:
delivery = pd.read_csv("../data/raw/deliveries.csv")
match = pd.read_csv("../data/raw/matches.csv")

In [60]:
match.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [61]:
match.shape

(756, 18)

In [62]:
delivery.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [63]:
total_score_df = delivery.groupby(["match_id","inning"]).sum()["total_runs"].reset_index()

In [64]:
total_score_df = total_score_df[total_score_df["inning"] == 1]

In [65]:
total_score_df['total_runs'] = total_score_df['total_runs'] + 1

In [66]:
total_score_df

      match_id  inning  total_runs
0            1       1         208
2            2       1         185
4            3       1         184
6            4       1         164
8            5       1         158
...        ...     ...         ...
1518     11347       1         144
1520     11412       1         137
1522     11413       1         172
1524     11414       1         156
1526     11415       1         153

[756 rows x 3 columns]

In [67]:
match_df = match.merge(total_score_df[["match_id","total_runs"]],left_on = "id", right_on = "match_id")

In [68]:
match_df

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_runs
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,208
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,2,185
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,3,184
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,4,164
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,5,158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi,11347,144
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould,11412,137
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN,11413,172
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin,11414,156
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong,11415,153

In [69]:
match_df["team1"].unique()

array(['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Delhi Daredevils', 'Kings XI Punjab',
       'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants',
       'Delhi Capitals'], dtype=object)

In [70]:
 teams = [
     "Sunrisers Hyderabad",
     'Mumbai Indians',
     'Royal Challengers Bangalore', 
     'Kolkata Knight Riders',
     'Kings XI Punjab',
     'Chennai Super Kings',
     'Rajasthan Royals',
     'Delhi Capitals',
     "Gujarat Titans",
      "Lucknow Super Giants"
 ]

In [71]:
match_df["team1"] = match_df["team1"].str.replace("Delhi Daredevils", "Delhi Capitals")
match_df["team2"] = match_df["team2"].str.replace("Delhi Daredevils", "Delhi Capitals")
match_df["team1"] = match_df["team1"].str.replace('Gujarat Lions', "Gujarat Titans")
match_df["team2"] = match_df["team2"].str.replace('Gujarat Lions', "Gujarat Titans")
match_df["team1"] = match_df["team1"].str.replace('Rising Pune Supergiants', "Lucknow Super Giants")
match_df["team2"] = match_df["team2"].str.replace('Rising Pune Supergiants', "Lucknow Super Giants")
match_df["team1"] = match_df["team1"].str.replace('Deccan Chargers',  'Sunrisers Hyderabad')
match_df["team2"] = match_df["team2"].str.replace('Deccan Chargers',  'Sunrisers Hyderabad')

In [72]:
match_df = match_df[match_df["team1"].isin(teams)]
match_df = match_df[match_df["team2"].isin(teams)]

In [73]:
match_df

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_runs
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,208
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Titans,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,3,184
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,5,158
5,6,IPL-2017,Hyderabad,09-04-2017,Gujarat Titans,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN,6,136
6,7,IPL-2017,Mumbai,09-04-2017,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN,7,179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi,11347,144
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould,11412,137
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN,11413,172
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin,11414,156
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong,11415,153

In [74]:
match_df = match_df[match_df["dl_applied"] == 0]

In [75]:
match_df = match_df[['match_id','city','winner','total_runs']]

In [76]:
delivery_df = match_df.merge(delivery,on = 'match_id')

In [77]:
delivery_df = delivery_df[delivery_df['inning'] == 2]

In [78]:
delivery_df.head(50)

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,0,0,0,1,0,1,NaN,NaN,NaN
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
128,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,0,0,0,2,0,2,NaN,NaN,NaN
129,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,0,0,0,4,0,4,NaN,NaN,NaN
130,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,6,Mandeep Singh,...,0,0,0,0,4,0,4,NaN,NaN,NaN
131,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,1,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
132,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,2,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
133,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,3,CH Gayle,...,0,0,0,0,1,0,1,NaN,NaN,NaN
134,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,4,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
135,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,5,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
136,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,6,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
137,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,1,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
138,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,2,CH Gayle,...,0,0,0,0,4,0,4,NaN,NaN,NaN
139,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,3,CH Gayle,...,0,0,0,0,1,0,1,NaN,NaN,NaN
140,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,4,Mandeep Singh,...,0,0,0,0,4,0,4,NaN,NaN,NaN
141,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,5,Mandeep Singh,...,0,0,0,0,1,0,1,NaN,NaN,NaN
142,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,6,CH Gayle,...,0,0,0,0,6,0,6,NaN,NaN,NaN
143,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,1,Mandeep Singh,...,0,0,0,0,1,0,1,NaN,NaN,NaN
144,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,2,CH Gayle,...,0,0,0,0,6,0,6,NaN,NaN,NaN
145,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,3,CH Gayle,...,0,0,0,0,2,0,2,NaN,NaN,NaN
146,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,4,CH Gayle,...,0,0,0,0,0,1,1,NaN,NaN,NaN
147,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,5,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
148,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,6,CH Gayle,...,0,0,0,0,1,0,1,NaN,NaN,NaN
149,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,7,Mandeep Singh,...,0,0,0,0,4,0,4,NaN,NaN,NaN
150,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,1,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
151,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,2,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
152,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,3,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
153,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,4,CH Gayle,...,0,0,0,0,0,1,1,NaN,NaN,NaN
154,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,5,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
155,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,6,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
156,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,7,CH Gayle,...,0,0,0,0,4,0,4,NaN,NaN,NaN
157,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,1,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
158,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,2,Mandeep Singh,...,0,0,0,0,4,0,4,NaN,NaN,NaN
159,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,3,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
160,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,4,Mandeep Singh,...,0,0,0,0,0,0,0,Mandeep Singh,bowled,NaN
161,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,5,TM Head,...,0,0,0,0,2,0,2,NaN,NaN,NaN
162,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,6,TM Head,...,0,0,0,0,0,0,0,NaN,NaN,NaN
163,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,1,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
164,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,2,CH Gayle,...,0,0,0,0,6,0,6,NaN,NaN,NaN
165,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,3,CH Gayle,...,0,0,0,0,0,0,0,CH Gayle,caught,DA Warner
166,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,4,TM Head,...,0,0,0,0,0,0,0,NaN,NaN,NaN
167,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,5,TM Head,...,0,0,0,0,1,0,1,NaN,NaN,NaN
168,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,6,KM Jadhav,...,0,0,0,0,0,0,0,NaN,NaN,NaN
169,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,1,TM Head,...,0,0,0,0,4,0,4,NaN,NaN,NaN
170,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,2,TM Head,...,0,0,0,0,2,0,2,NaN,NaN,NaN
171,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,3,TM Head,...,0,0,0,0,1,0,1,NaN,NaN,NaN
172,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,4,KM Jadhav,...,0,0,0,0,1,0,1,NaN,NaN,NaN
173,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,5,TM Head,...,0,0,0,0,1,0,1,NaN,NaN,NaN
174,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,8,6,KM Jadhav,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [79]:
 delivery_df["current_score"] =delivery_df.groupby('match_id')['total_runs_y'].cumsum()

In [80]:
delivery_df["runs_left"] = delivery_df["total_runs_x"] - delivery_df['current_score']

In [81]:
delivery_df["ball_left"] = 120 - ((delivery_df['over'] - 1) * 6 + delivery_df['ball'])

In [82]:
 delivery_df

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,runs_left,ball_left
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,1,0,1,NaN,NaN,NaN,1,207,119
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,NaN,NaN,NaN,1,207,118
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,NaN,NaN,NaN,1,207,117
128,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,2,0,2,NaN,NaN,NaN,3,205,116
129,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,4,0,4,NaN,NaN,NaN,7,201,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158383,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,0,1,0,1,NaN,NaN,NaN,152,1,4
158384,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,0,2,0,2,NaN,NaN,NaN,154,-1,3
158385,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,0,1,0,1,SR Watson,run out,KH Pandya,155,-2,2
158386,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,0,2,0,2,NaN,NaN,NaN,157,-4,1
158387,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,0,0,0,0,SN Thakur,lbw,NaN,157,-4,0

In [83]:
delivery_df['is_wicket'] = delivery_df['player_dismissed'].notnull().astype(int)
delivery_df['wickets_fallen'] = delivery_df.groupby('match_id')['is_wicket'].cumsum()
delivery_df['wickets_left'] = 10 - delivery_df['wickets_fallen']
delivery_df[['player_dismissed', 'is_wicket', 'wickets_fallen', 'wickets_left']].tail(5)

       player_dismissed  is_wicket  wickets_fallen  wickets_left
158383              NaN          0               5             5
158384              NaN          0               5             5
158385        SR Watson          1               6             4
158386              NaN          0               6             4
158387        SN Thakur          1               7             3

In [84]:
delivery_df["crr"] = (delivery_df["current_score" ] * 6)/(120 - delivery_df["ball_left"])

In [85]:
delivery_df['rrr'] = (delivery_df['runs_left'] * 6)/ delivery_df["ball_left"]

In [86]:
delivery_df

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,dismissal_kind,fielder,current_score,runs_left,ball_left,is_wicket,wickets_fallen,wickets_left,crr,rrr
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,NaN,NaN,1,207,119,0,0,10,6.000000,10.436975
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,NaN,NaN,1,207,118,0,0,10,3.000000,10.525424
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,NaN,NaN,1,207,117,0,0,10,2.000000,10.615385
128,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,NaN,NaN,3,205,116,0,0,10,4.500000,10.603448
129,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,NaN,NaN,7,201,115,0,0,10,8.400000,10.486957
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158383,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,NaN,NaN,152,1,4,0,5,5,7.862069,1.500000
158384,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,NaN,NaN,154,-1,3,0,5,5,7.897436,-2.000000
158385,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,run out,KH Pandya,155,-2,2,1,6,4,7.881356,-6.000000
158386,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,NaN,NaN,157,-4,1,0,6,4,7.915966,-24.000000
158387,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,lbw,NaN,157,-4,0,1,7,3,7.850000,-inf

In [87]:
def result(row):
    return 1 if row["batting_team"] == row['winner'] else 0

In [88]:
delivery_df['result'] = delivery_df.apply(result, axis = 1)

In [89]:
final_df = delivery_df[["batting_team", "bowling_team", "city", "runs_left", "ball_left", "wickets_left", "total_runs_x", "crr", "rrr", "result"]]

In [90]:
final_df.sample(final_df.shape[0])

,batting_team,bowling_team,city,runs_left,ball_left,wickets_left,total_runs_x,crr,rrr,result
115502,Kolkata Knight Riders,Rajasthan Royals,Mumbai,136,80,8,200,9.600000,10.200000,0
118726,Kolkata Knight Riders,Sunrisers Hyderabad,Hyderabad,23,27,8,143,7.741935,5.111111,1
66375,Kings XI Punjab,Mumbai Indians,Mumbai,17,9,6,164,7.945946,11.333333,1
36062,Royal Challengers Bangalore,Deccan Chargers,Johannesburg,123,96,9,144,5.250000,7.687500,0
3752,Delhi Daredevils,Sunrisers Hyderabad,Hyderabad,153,94,9,192,9.000000,9.765957,0
...,...,...,...,...,...,...,...,...,...,...
3352,Kings XI Punjab,Sunrisers Hyderabad,Hyderabad,6,2,1,160,7.830508,18.000000,0
146879,Rajasthan Royals,Chennai Super Kings,Chennai,183,114,9,183,0.000000,9.631579,0
139947,Rajasthan Royals,Chennai Super Kings,Jaipur,88,53,8,189,9.044776,9.962264,1
29980,Rajasthan Royals,Royal Challengers Bangalore,Centurion,90,95,10,106,3.840000,5.684211,1
46371,Deccan Chargers,Chennai Super Kings,Nagpur,17,13,6,139,6.841121,7.846154,1

In [91]:
final_df.sample()

,batting_team,bowling_team,city,runs_left,ball_left,wickets_left,total_runs_x,crr,rrr,result
676,Delhi Daredevils,Royal Challengers Bangalore,Bangalore,47,37,5,158,8.024096,7.621622,0

In [92]:
final_df['batting_team'].unique()

array(['Royal Challengers Bangalore', 'Kolkata Knight Riders',
       'Delhi Daredevils', 'Sunrisers Hyderabad', 'Mumbai Indians',
       'Kings XI Punjab', 'Gujarat Lions', 'Rajasthan Royals',
       'Chennai Super Kings', 'Deccan Chargers',
       'Rising Pune Supergiants', 'Delhi Capitals'], dtype=object)

In [93]:
team_map = {
    'Delhi Daredevils': 'Delhi Capitals',
    'Deccan Chargers': 'Sunrisers Hyderabad',
    "Gujarat Lions" : "Gujarat Titans",
    "Rising Pune Supergiants" : "Lucknow Super Giants"
    
}
for col in ['batting_team', 'bowling_team']:
    final_df[col] = final_df[col].replace(team_map)

C:\Users\Victus\AppData\Local\Temp\ipykernel_7340\3711315766.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df[col] = final_df[col].replace(team_map)

In [94]:
final_df.sample(final_df.shape[0])

,batting_team,bowling_team,city,runs_left,ball_left,wickets_left,total_runs_x,crr,rrr,result
36819,Delhi Capitals,Kings XI Punjab,Chandigarh,115,92,8,143,6.000000,7.500000,1
125187,Delhi Capitals,Kings XI Punjab,Chandigarh,130,83,10,182,8.432432,9.397590,0
115550,Kolkata Knight Riders,Rajasthan Royals,Mumbai,66,34,5,200,9.348837,11.647059,0
151805,Rajasthan Royals,Kings XI Punjab,Mohali,64,33,8,191,8.758621,11.636364,0
112220,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata,149,105,8,168,7.600000,8.514286,0
...,...,...,...,...,...,...,...,...,...,...
12133,Mumbai Indians,Kings XI Punjab,Chandigarh,181,114,10,183,2.000000,9.526316,0
93415,Chennai Super Kings,Sunrisers Hyderabad,Sharjah,14,16,6,146,7.615385,5.250000,1
98482,Kings XI Punjab,Sunrisers Hyderabad,Hyderabad,81,65,7,206,13.636364,7.476923,1
26323,Rajasthan Royals,Delhi Capitals,Centurion,119,93,9,144,5.555556,7.677419,1
101364,Delhi Capitals,Mumbai Indians,Mumbai,152,108,10,174,11.000000,8.444444,0

In [95]:
final_df.sample()

,batting_team,bowling_team,city,runs_left,ball_left,wickets_left,total_runs_x,crr,rrr,result
109184,Sunrisers Hyderabad,Mumbai Indians,Mumbai,31,12,5,158,7.055556,15.5,0

In [96]:
final_df['bowling_team'].unique()

array(['Sunrisers Hyderabad', 'Gujarat Titans',
       'Royal Challengers Bangalore', 'Kolkata Knight Riders',
       'Kings XI Punjab', 'Delhi Capitals', 'Mumbai Indians',
       'Chennai Super Kings', 'Rajasthan Royals', 'Lucknow Super Giants'],
      dtype=object)

In [97]:
final_df.to_csv('../data/processed/final1_df.csv', index=False)